### ISSUE TITLE
Windows mingw compile error

### ISSUE THREAD

**Issue by mohammad-nazari** [oatpp/example-api-client#5] opened 2020-10-17 15:35 UTC
ConnectionProvider.cpp:300:5: error: 'inet_ntop' was not declared in this scope inet_ntop(AF_INET, &sockAddress->sin_addr, strIp, INET_ADDRSTRLEN);
Windows, MinGW64, g++, cmake, clion

**Comment by lganzzzo** [comment] 2020-10-17 15:46
Closing this as a duplicate of https://github.com/oatpp/oatpp/issues/324

**Closed as completed by lganzzzo** 2020-10-17 15:46 UTC
Labels: duplicate
